@DrawGheterInfrastructure_HostAddress = http://localhost:5001/api

GET {{DrawGheterInfrastructure_HostAddress}}/test/
Accept: application/json

###

GET {{DrawGheterInfrastructure_HostAddress}}/test/9
Accept: application/json

###
